### ISSUE TITLE
Doesn`t work in Webkit Browsers

### ISSUE THREAD

**Issue by teamayu** [eumatheusgomes/sidenav#1]
Nice plugin, thank you. 

It doesn`t appear to work in any webkit browsers, the menu is open on load and doesn`t work. Same in the demo.

**Comment by teamayu** [comment]
I figured it out, so for anyone else who has the same problem you need to use:

-webkit-transform: translate(-262px, 0);
-webkit-transition: -webkit-transform .3s;

and

-webkit-transform: translate(0, 0);

**Comment by eumatheusgomes** [comment]
Since we're already using a preprocessor, just include some tool like autoprefixer and you're good to go.

**Comment by teamayu** [comment]
Ok, thanks.

**Comment by ivardesign** [comment]
Tried on iPad2/Firefox: online demo menu opens but won't close.  Same result on self install (after adding -webkit prefixes as previously mentioned) testing again with iPad2/Firefox and iPhone5 Safari and Firefox.

Works great on non-touch.  Will keep hacking.  Maybe a ES fix?

**Comment by ivardesign** [comment]
I tried adding jQ Mobile and changing from click to tap.  This works on the touch devices, but now it won't stay open on the non-touch screens.
